app/Http/routes.php
<?php
Route::get('blog.html', 'BlogController@index');
Route::get('san-pham.html', function(){
    return view('products.index');
});
Route::get('san-pham/chi-tiet.html', function(){
    return view('products.show');
});

Route::get('tin-tuc.html', function(){
    return view('blog/index');
});

Route::get('tin-tuc/chi-tiet.html', function(){
    return view('blog/show');
});

Route::get('trang', function(){
    return view('page-default');
});


Route::get('sitemap.xml', ['as' => 'sitemap.xml', 'uses' => 'ToolsController@sitemap']);

//Backend-----------------------------------------------------------------------------------------------------------
Route::controller('auth/password', 'Auth\PasswordController', [
    'getEmail' => 'auth.password.email',
    'getReset' => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'getLogout' => 'auth.logout'
]);

//Advertising
Route::resource('backend/ads', 'Backend\AdsController', ['except' => ['show', 'create']]);
Route::post('backend/ads/bulk', ['as' => 'backend.ads.bulk', 'uses' => 'Backend\AdsController@bulk']);
Route::get('backend/ads/{id}/duplicate', ['as' => 'backend.ads.duplicate', 'uses' => 'Backend\AdsController@duplicate']);
Route::get('backend/ads/{id}/confirm', ['as' => 'backend.ads.confirm', 'uses' => 'Backend\AdsController@confirm']);

Route::get('blogcategories/{categories}/confirm', ['as' => 'backend.blogcategories.confirm', 'uses' => 'Backend\BlogCategoriesController@confirm']);
Route::post('backend/blogcategories/bulk', ['as' => 'backend.blogcategories.bulk', 'uses' => 'Backend\BlogCategoriesController@index']);
Route::resource('backend/blogcategories', 'Backend\BlogCategoriesController', ['except' => ['show']]);
Route::get('backend/productcategories/{categories}/confirm', ['as' => 'backend.productcategories.confirm', 'uses' => 'Backend\ProductCategoriesController@confirm']);
Route::resource('backend/productcategories', 'Backend\ProductCategoriesController', ['except' => ['show']]);
Route::resource('backend/messages', 'Backend\MessagesController', ['except' => ['show']]);
Route::get('backend/messages/{id}/mark-read', ['as' => 'backend.messages.markread', 'uses' => 'Backend\MessagesController@markRead']);
Route::get('backend/messages/{id}/delete', ['as' => 'backend.messages.delete', 'uses' => 'Backend\MessagesController@delete']);
//Menu
Route::get('backend/menus/{id}/confirm', ['as' => 'backend.menus.confirm', 'uses' => 'Backend\MenusController@confirm']);
Route::post('backend/menus/additem', ['as' => 'backend.menus.additem', 'uses' => 'Backend\MenusController@addItem']);
Route::post('backend/menus/save', ['as' => 'backend.menus.save', 'uses' => 'Backend\MenusController@saveMenu']);
Route::post('backend/menus/order', ['as' => 'backend.menus.order', 'uses' => 'Backend\MenusController@order']);
Route::get('backend/menus/{id}/remove', ['as' => 'backend.menus.remove', 'uses' => 'Backend\MenusController@remove']);
Route::resource('backend/menus', 'Backend\MenusController', ['except' => ['show']]);

Route::get('backend/themeoption', ['as' => 'backend.themeoption.index', 'uses' => 'Backend\ThemeOptionController@index']);
Route::post('backend/themeoption/save', ['as' => 'backend.themeoption.save', 'uses' => 'Backend\ThemeOptionController@save']);
Route::resource('backend/products', 'Backend\ProductsController');
Route::get('product/detach-image/{image_id}/{product_id}', 'Backend\ProductsController@detachImage');
Route::get('product/detach-option/{option_id}/{product_id}/{option_value_id}', 'Backend\ProductsController@detachOption');
Route::get('product/add-option/{type}/{length}', 'Backend\ProductsController@addOptionAjax');
Route::resource('backend/orders', 'Backend\OrdersController');
Route::get('backend/order/{id}/update_status/{status_id}', ['as' => 'backend.order.update_status', 'uses' => 'Backend\OrdersController@update_status']);
//File manager
Route::resource('backend/filemanager', 'Backend\FileManagerController');
Route::post('backend/get_subdirectories',  'Backend\FileManagerController@get_subdirectories');
Route::get('backend/orders/{id}/confirm', ['as' => 'backend.orders.confirm', 'uses' => 'Backend\OrdersController@confirm']);
Route::get('backend/attributegroups/{id}/confirm', ['as' => 'backend.attributegroups.confirm', 'uses' => 'Backend\AttributeGroupsController@confirm']);
Route::get('backend/attributes/{id}/confirm', ['as' => 'backend.attributes.confirm', 'uses' => 'Backend\AttributesController@confirm']);
Route::resource('backend/attributegroups', 'Backend\AttributeGroupsController');
Route::resource('backend/attributes', 'Backend\AttributesController');

Route::get('admin', ['as' => 'admin', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend', ['as' => 'backend', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/dashboard', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/products/{product}/confirm', ['as' => 'backend.products.confirm', 'uses' => 'Backend\ProductsController@confirm']);
Route::get('/home', function(){
   return view('backend');
});
Route::resource('backend/setting', 'Backend\SettingsController');
Route::resource('backend/branch', 'Backend\BranchesController');

//FrontEnd
Route::get('file/get/{filename}', [
    'as' => 'getentry', 'uses' => 'FilesController@get']);

Route::get('image/products/{id}/{slug}.jpg', [
    'as' => 'product_img', 'uses' => 'FilesController@get_product_image']);


Route::get('/', 'HomeController@index');






//FrontEnd

Route::post('product/order/place-order', ['as' => 'order.place', 'uses' => 'ProductsController@placeOrder']);
Route::post('product/review', ['as' => 'product.review', 'uses' => 'ProductsController@review']);
Route::post('product/update-price',  'ProductsController@updateShowPagePrice');
Route::get('tool/slug/genslug/{string}', 'ToolsController@genSlug');
Route::get('getattributehtml/{id}', 'ToolsController@getAttributeHtml');
Route::post('render-new-product-image', 'ToolsController@renderNewProductImage');
Route::get('getoptionvalue/{id}', 'ToolsController@getOptionValue');
Route::get('get-district/{province_id}', 'ToolsController@getDistrict');
Route::get('selected-ship-to-different-address', 'ToolsController@toggleShippingAddress');
Route::get('get-ward/{district_id}', 'ToolsController@getWard');
Route::get('apply-coupon/{code}', 'HomeController@applyCoupon');

Route::get('create-admin-role', 'ToolsController@createrole');

Route::get('session', function(){
    dd(session());
});

Route::resource('user', 'UsersController', ['except' => ['create', 'destroy', 'show', 'index']]);

Route::get('login.html', [
    'as' => 'users.login', 'uses' => 'UsersController@login']);

Route::get('register.html', [
    'as' => 'users.register', 'uses' => 'UsersController@register']);

Route::get('profile.html', [
    'as' => 'user.profile', 'uses' => 'UsersController@profile']);

Route::post('postlogin', [
    'as' => 'user.login.post', 'uses' => 'UsersController@postLogin']);
Route::get('postregister', [
    'as' => 'user.register.post', 'uses' => 'UsersController@postRegister']);


Route::get('tags/product/{slug}.{id}.html', ['as' => 'product.tag', 'uses' => 'ProductsController@tag']);
Route::get('user/github/login', ['as' => 'user.github.login', 'uses' => 'UsersController@githubLogin']);
Route::get('user/facebook/login', ['as' => 'user.facebook.login', 'uses' => 'UsersController@facebookLogin']);
Route::get('user/facebook/login/step/2', ['as' => 'user.facebook.login.step2', 'uses' => 'UsersController@facebookLoginStep2']);
Route::get('user/google/login', ['as' => 'user.google.login', 'uses' => 'UsersController@googleLogin']);
Route::get('user/google/login/step/2', ['as' => 'user.google.login.step2', 'uses' => 'UsersController@googleLoginStep2']);
Route::get('user/twitter/login', ['as' => 'user.twitter.login', 'uses' => 'UsersController@twitterLogin']);
Route::get('user/twitter/login/step/2', ['as' => 'user.twitter.login.step2', 'uses' => 'UsersController@twitterLoginStep2']);

Route::get('cart/information', function(){
   return view('cart.information');
});


//Product
//Product-Frontend
Route::get('product/dat-hang-thanh-cong.html', ['as' => 'product.ordersuccess', 'uses' => 'ProductsController@orderSuccess']);

Route::get('product/checkout', ['as' => 'product.checkout', 'uses' => 'ProductsController@checkout']);
Route::resource('product', 'ProductsController');
Route::get('product.html', ['as' => 'product', 'uses' => 'ProductsController@index']);

Route::post('product/add-to-cart', ['as' => 'cart.add', 'uses' => 'CartController@add']);
Route::get('cart/view-cart', ['as' => 'cart.show', 'uses' => 'CartController@show']);
Route::get('cart/clear', ['as' => 'cart.clear', 'uses' => 'CartController@clear']);
Route::get('cart/delete/{key}', ['as' => 'cart.delete', 'uses' => 'CartController@delete']);
Route::get('cart/delete/ajax/{key}', ['as' => 'cart.ajax.delete', 'uses' => 'CartController@deleteAjax']);
Route::get('cart/update/{key}/{quantity}', ['as' => 'cart.update', 'uses' => 'CartController@update']);
Route::get('product/{id}-{slug}.html', ['as' => 'product.show', 'uses' => 'ProductsController@show']);
//Product--Backend
Route::post('backend/products/bulk', ['as' => 'backend.products.bulk', 'uses' => 'Backend\ProductsController@index']);
Route::get('backend/options/{options}/confirm', ['as' => 'backend.options.confirm', 'uses' => 'Backend\OptionsController@confirm']);
Route::post('backend/options/bulk', ['as' => 'backend.options.bulk', 'uses' => 'Backend\OptionsController@index']);
Route::resource('backend/options', 'Backend\OptionsController');
Route::get('backend/coupons/{id}/confirm', ['as' => 'backend.coupons.confirm', 'uses' => 'Backend\CouponsController@confirm']);
Route::post('backend/coupons/bulk', ['as' => 'backend.coupons.bulk', 'uses' => 'Backend\CouponsController@index']);

resources/views/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demo.interface.club/limitless/layout_1/LTR/login_simple.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 10 Jan 2016 17:09:18 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/core.css" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/components.css" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/colors.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{{url('assets')}}/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="{{url('assets')}}/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="{{url('assets')}}/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{url('assets')}}/js/plugins/loaders/blockui.min.js"></script>
    <!-- /core JS files -->


    <!-- Theme JS files -->
    <script type="text/javascript" src="{{url('assets')}}/js/core/app.js"></script>
    <!-- /theme JS files -->

</head>

<body>


<!-- Page container -->
<div class="page-container login-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                <!-- Simple login form -->
                @yield('content')
                <!-- /simple login form -->


                <!-- Footer -->
                <div class="footer text-muted">
                    &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
                </div>
                <!-- /footer -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>

<!-- Mirrored from demo.interface.club/limitless/layout_1/LTR/login_simple.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 10 Jan 2016 17:09:18 GMT -->
</html>

resources/views/filemanager.blade.php
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <base href="{{ url() }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet"
          type="text/css">
    <link href="{{url('assets')}}/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="{{url('assets')}}/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="{{url('vendor')}}/filemanager/css/filemanager.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{{url('assets')}}/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="{{url('assets')}}/js/core/libraries/bootstrap.min.js"></script>
    <!-- /core JS files -->


</head>

<body style="background: #fff">


<!-- Page container -->
<div class="page-container login-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content container-fluid">

                <ul class="functions-button list-unstyled list-inline">
                    <li><button type="button" class="btn btn-success">Chọn</button></li>
                </ul>

                <div class="line"></div>


                <div class="row">
                    <div class="col-sm-3 list-folders" style="border-right: 1px solid #e5e5e5; min-height: 1000px">
                        <ul class="list-unstyled">
                            @foreach($folders as $folder)
                                <li class="{{ (check_directory_child($folder)) ? 'has-sub' : '' }}">
                                    <span>{{ str_limit($folder, 15) }}</span>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="col-sm-9">
                        sdfsdf
                    </div>
                </div>

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->
<script src="{{ url() }}/vendor/filemanager/js/scripts.js"></script>
</body>

</html>

resources/views/flash.blade.php
@if(session()->has('flash_message'))<!-- Panel _start -->
<div class="flash alert alert-{!! session('flash_message.level') !!} alert-styled-left">
    <span class="text-semibold">{!! session('flash_message.title') !!}!</span> {!! session('flash_message.message') !!}
    <div class="heading-elements">
        <ul class="icons-list">
            <li><a class="close" data-action="close"></a></li>
        </ul>
    </div>
</div>
@endif

resources/views/invoice.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    @include('partials.backend.metadata')

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{ url('assets') }}/js/plugins/forms/styling/uniform.min.js"></script>
    <script type="text/javascript" src="{{ url('assets') }}/js/core/app.js"></script>
    <script type="text/javascript" src="{{ url('assets') }}/js/pages/invoice_grid.js"></script>
    <!-- /theme JS files -->

</head>

<body class="sidebar-xs">

<!-- Main navbar -->
@include('partials.backend.navbar')
<!-- /main navbar -->


<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main sidebar -->
        @include('partials.backend.sidebar')
        <!-- /main sidebar -->


        <!-- Secondary sidebar -->
        @include('partials.backend.secondary-sidebar')
        <!-- /secondary sidebar -->


        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Page header -->
            <div class="page-header page-header-transparent">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> @yield('title')</h4>

                        <ul class="breadcrumb position-right">
                            <li><a href="{{ route('backend') }}">Home</a></li>
                            <li><a href="">Đơn hàng</a></li>
                        </ul>
                    </div>

                    <div class="heading-elements">
                        <a href="{{ route('backend.orders.create') }}" class="btn bg-blue btn-labeled heading-btn"><b><i class="icon-calculator"></i></b> Tạo đơn hàng</a>
                        <a href="{{ route('backend.setting.index') }}" class="btn btn-default btn-icon heading-btn"><i class="icon-gear"></i></a>
                    </div>
                </div>
            </div>
            <!-- /page header -->


            <!-- Content area -->
            <div class="content">

                @yield('content');

                <!-- Footer -->
                @include('partials.backend.footer')
                <!-- /footer -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>
</html>