modules/Gallery/Http/routes.php
<?php

Route::group(['prefix' => 'gallery', 'namespace' => 'Modules\Gallery\Http\Controllers'], function()
{
	Route::group(['prefix' => 'backend', 'namespace' => '\Backend'],  function(){
		//Category
		Route::resource('categories', 'CategoriesController');
		Route::get('categories/{id}/confirm', ['as' => 'gallery.backend.categories.confirm', 'uses'	=> 'CategoriesController@confirm']);
		Route::post('categories/bulk', ['as' => 'gallery.backend.categories.bulk', 'uses'	=> 'CategoriesController@bulk']);
		Route::get('categories/{id}/duplicate', ['as' => 'gallery.backend.categories.duplicate', 'uses'	=> 'CategoriesController@duplicate']);
		Route::post('image-name', ['as' => 'gallery.backend.image.name', 'uses'	=> 'AlbumsController@imageName']);
		//Product
		Route::resource('albums', 'AlbumsController');
		Route::get('albums/{id}/confirm', ['as' => 'gallery.backend.albums.confirm', 'uses'	=> 'AlbumsController@confirm']);
		Route::get('albums/detach-image/{album_id}/{image_id}', ['as' => 'gallery.backend.albums.detachImage', 'uses'	=> 'AlbumsController@detachImage']);
		Route::post('albums/bulk', ['as' => 'gallery.backend.albums.bulk', 'uses'	=> 'AlbumsController@bulk']);
		Route::get('albums/{id}/duplicate', ['as' => 'gallery.backend.albums.duplicate', 'uses'	=> 'AlbumsController@duplicate']);

		Route::resource('orders', 'OrdersController');
		Route::resource('popularphotos', 'PopularPhotosController');


	});
	Route::get('/', 'GalleryController@index');
	Route::get('album.html', ['as' => 'gallery.galbum.index', 'uses' => 'AlbumsController@index']);
	Route::get('album/{id}.{slug}.html', ['as' => 'gallery.album.show', 'uses' => 'AlbumsController@show']);
	Route::get('album/order/{image_id}_{album_slug}.html', ['as' => 'gallery.album.order', 'uses' => 'AlbumsController@order']);
	Route::post('album/order', ['as' => 'gallery.album.postOrder', 'uses' => 'AlbumsController@postOrder']);
	Route::get('category/login-required', ['as' => 'gallery.category.login', 'uses' => 'CategoriesController@loginRequired']);
	Route::post('category/login', ['as' => 'gallery.category.postLogin', 'uses' => 'CategoriesController@postLogin']);
	Route::get('category/{slug}.html', ['as' => 'gallery.category.show', 'uses' => 'CategoriesController@show']);
	Route::get('tag/{slug}.html', ['as' => 'gallery.tag', 'uses' => 'GalleryController@tag']);
	Route::resource('albums', 'AlbumsController', ['excerpt' => 'show']);
	Route::post('render-new-album-image', 'GalleryController@renderNewProductImage');


});

modules/Gallery/Entities/Album.php
<?php namespace Modules\Gallery\Entities;
   
use Illuminate\Database\Eloquent\Model;
use App\Models\Tag;

class Album extends Model {

    protected $fillable = [
        'name',
        'slug',
        'order_number',
        'thumbnail',
        'seo_title',
        'description',
        'home',
        'suggest',
        'short_description',
        'meta_description',
        'feature'
    ];

    protected $table = 'gallery_albums';


    /**
     * Các ảnh của sản phẩm
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function images()
    {
        return $this->belongsToMany('Modules\Gallery\Entities\Image', 'gallery_album_image', 'album_id', 'image_id');
    }


    /**
     * Tag
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'gallery_album_tag', 'album_id', 'tag_id');
    }

    /**
     * Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('Modules\Gallery\Entities\Category', 'gallery_album_category', 'album_id', 'category_id');
    }


    /**
     * Bind Categories
     *
     * @return array
     */
    public function getCategoryListAttribute()
    {
        $list = [];
        $categories = $this->categories()->get();
        foreach($categories as $category){
            $list[] = $category->id;
        }
       return $list;
    }

}

modules/Gallery/Http/Controllers/AlbumsController.php
<?php namespace Modules\Gallery\Http\Controllers;

use Illuminate\Http\Request;
use Modules\Gallery\Entities\Album;
use Modules\Gallery\Entities\Image;
use Modules\Gallery\Entities\Order;
use Mail;
use Pingpong\Modules\Routing\Controller;

class AlbumsController extends Controller {
	
	public function index()
	{
		$albums = Album::paginate(12);

		return mview('gallery::albums.index', compact('albums'));
	}


	/**
	 * @param $id
	 * @param $slug
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\View
	 */
	public function show($id, $slug)
	{

		$query = Album::where('slug', $slug)->where('id', $id);
		//Không tồn tại sẽ redirect
		if($query->count() == 0){
			return redirect();
		}

		$album = $query->with('tags')->first();
		return mview('gallery::albums.show', compact('album'));
	}


	public function order($image_id, $album_slug)
	{
		$imgQuery = Image::where('id', $image_id);
		$albumQuery = Album::where('slug', $album_slug);
		if($imgQuery->count() == 0 || $albumQuery->count() == 0){
			return redirect();
		}

		$data['image'] = $imgQuery->first();
		$data['album'] = $albumQuery->first();

		return mview('gallery::albums.order', $data);
	}

	public function postOrder(Request $request)
	{
		$this->validate($request, [
			'name'	=> 'required|max:60',
			'phone'	=> 'required|max:25',
			'address'	=> 'required',
			'note'	=> 'required|max:1000',
			'email'	=> 'required|email|max:150',
			'image_id'	=> 'required|exists:gallery_images,id',
			'album_id'	=> 'required|exists:gallery_albums,id'
		]);

		$album = Album::findOrFail($request->input('album_id'));
		$imageName = image_code(Image::findOrFail($request->input('image_id')), $album);

		$data=$request->all();
		$data['imageName'] = $imageName;

		Order::create($request->all());

		Mail::send('emails.order', ['data' => $data], function ($m) use ($request) {
			$m->from('info@huyenhoang.com', 'Huyền Hoàng');

			$m->to(get_settings('email'), $request->input('name'))->subject('Khách hàng đặt mua ảnh từ www.huyenhoang.com');
		});

		flash()->success('Thành công, ', 'Chúng tôi đã nhận được đơn hàng của quý khách, sẽ liên lạc lại sớm');

		return redirect()->back();
	}
	
}

modules/Gallery/Http/Controllers/Backend/AlbumsController.php
<?php namespace Modules\Gallery\Http\Controllers\Backend;

use App\Models\Tag;
use Modules\Gallery\Entities\Category;
use Modules\Gallery\Entities\Image;
use Modules\Gallery\Entities\Album;
use Modules\Gallery\Http\Requests\StoreAlbumRequest;
use Cocur\Slugify\Slugify;
use Illuminate\Http\Request;
use Modules\Gallery\Http\Requests\UpdateAlbumRequest;

class AlbumsController extends Controller
{


    public function __construct()
    {
        parent::__contruct();
    }

    /**
     * Liệt kê danh sách tất cả album
     *
     * @return \View
     */
    public function index()
    {
        $albums = Album::orderBy('created_at', 'desc')->paginate(config('app.items_per_page'));

        return module_view('gallery', 'backend.albums.index', compact('albums'));
    }


    public function bulk(Request $request, Album $album)
    {
        bulk_delete($request, $album);

        return redirect()->back();
    }


    /**
     * Form Tạo album
     *
     * @param Album $album
     * @return \View
     */
    public function create(Album $album)
    {
        $categories = $this->getCategories();

        //Không thể tạo album nếu không tồn tại danh mục
        if (count($categories) == 0) {
            flash(trans('gallery::album.create_cat_first'));
            return redirect(route('gallery.backend.albums.index'));
        }

        //Mặc định phải có tagString
        $tagString = '';

        return module_view('gallery', 'backend.albums.form', compact('album', 'tagString', 'categories'));
    }


    /**
     * Dựng các danh mục thành cây
     *
     * @return array
     */
    protected function getCategories()
    {
        $catItems = Category::all()->toHierarchy();

        $categories = [];

        foreach ($catItems as $node) {
            $categories += arrange_categories($node);
        }

        return $categories;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreAlbumRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAlbumRequest $request)
    {
        //Lưu album
        $album = Album::create($request->all());

        //Attach Tags
        if ($request->input('tags') != '') {
            $album->tags()->attach($this->tagsProcess($request->input('tags')));
        }

        //Xử lý hình ảnh
        if ($request->input('images')) {
            foreach ($request->input('images') as $image) {
                $savedImage = $this->image_process($image);
                $album->images()->attach($savedImage->id);
            }
        }

        //Attach categories
        $album->categories()->attach($request->input('category_list'));

        flash()->success('Thành công.', 'Bạn đã thêm thành công album');

        switch ($request->input('button')) {
            case 'save':
                return redirect(route('gallery.backend.albums.edit', $album->id));
            default:
                return redirect(route('gallery.backend.albums.index'));
        }


    }


    /**
     *
     * @param $imageID
     * @param $albumID
     */
    public function detachImage($imageID, $albumID)
    {
        $album = Album::findOrFail($albumID);
        $album->images()->detach($imageID);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tagString = '';
        $album = Album::findOrFail($id);

        if ($album->tags->count() > 0) {
            foreach ($album->tags->toArray() as $tag) {
                $tagString .= $tag['name'] . ',';
            }
        }

        $categories = $this->getCategories();
        return module_view('gallery','backend.albums.form', compact('album', 'tagString', 'categories'));
    }

    /**
     * Cập nhật album
     *
     * @param UpdateAlbumRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAlbumRequest $request, $id)
    {
        //Update album
        $album = Album::findOrFail($id);

        //Sync the tags for this post
        if ($request->input('tags') != '') {
            $album->tags()->sync($this->tagsProcess($request->input('tags')));
        }

        //Sync danh mục
        $album->categories()->sync($request->input('category_list'));

        //Xử lý thumbnail
        $album->update($request->all());

        //Xử lý hình ảnh
        if ($request->input('images')) {
            foreach ($request->input('images') as $image) {
                $processedImage = $this->image_process($image);
                $album->images()->detach($processedImage->id);
                $album->images()->attach($processedImage->id);
            }
        }

        //Thoát
        flash()->success(trans('common.success'), trans('gallery::album.update_success_message', ['name' => $album->name]));
        switch ($request->input('button')) {
            case 'save':
                return redirect(route('gallery.backend.albums.edit', $album->id));
            default:
                return redirect(route('gallery.backend.albums.index'));
        }


    }





    public function duplicate($id)
    {
        $album = Album::findOrFail($id);
        $albumCategories = $album->getCategoryListAttribute();
        $albumArray = $album->toArray();

        //Đặt slug mới
        $albumArray['slug'] = $albumArray['slug'] . '_';

        //Tạo mới album
        $album = Album::create($albumArray);

        //Vẫn giữ danh mục cũ
        $album->categories()->attach($albumCategories);

        flash(trans('gallery::album.duplicate_message', ['name' => $album->name]));

        return redirect(route('gallery.backend.albums.edit', $album->id));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $album = Album::findOrFail($id);

        $album->delete();

        flash()->success('Thành công', 'Bạn đã xóa album [' . $album->name . '] thành công');

        return redirect(route('gallery.backend.albums.index'));
    }


    public function imageName(Request $request)
    {
        $imageID = $request->input('imageID');
        $imageName = $request->input('imageName');

        Image::where('id', $imageID)->update(['name' => $imageName]);
    }


    /**
     * Album Delete Confirm
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm($id)
    {
        $album = Album::findOrFail($id);

        return mview('gallery::backend.albums.confirm', compact('album'));
    }


    /**
     * @param $option_id
     * @param $album_id
     */

    public function detachOption($option_id, $album_id, $option_value_id)
    {
        AlbumOption::where('option_id', $option_id)
            ->where('option_value_id', $option_value_id)
            ->where('album_id', $album_id)->delete();
        //
    }

    public function weareTestingThisController()
    {
        return view('AreYouOK');
    }

    public function addOptionAjax($option_id, $length)
    {
        $length++;
        if (!session('options_length')) {
            session()->put('options_length', $length);
        } else {
            $length = session('options_length');
            $length++;
            session()->put('options_length', $length);
            session()->save();
        }

        $option = Option::findOrFail($option_id);
        $values = OptionValue::lists('name', 'id');
        return view('backend.options.add_value', compact('option', 'values', 'length'));
    }


    /**
     * Xử lý Tag để lấy ra mảng tag của bài viết này
     *
     * @param $tagString
     * @return array
     */
    private function tagsProcess($tagString)
    {
        $tagList = explode(',', $tagString);
        $slugify = new Slugify();
        $returnTagsArray = array();
        //Duyệt qua các tag
        foreach ($tagList as $tagItem) {
            //Tạo tag slug
            $tagSlug = $slugify->slugify($tagItem);
            //Query xem có trùng không
            $query = Tag::where('slug', $tagSlug);

            if ($query->count() == 0) {
                $returnTagsArray[] = Tag::create(['name' => $tagItem, 'slug' => $tagSlug])->id;
            } else {
                $returnTagsArray[] = $query->first()->id;
            }

        }
        return $returnTagsArray;
    }


    /**
     * Thêm ảnh
     *
     * @param $file_path
     * @return static
     */
    private function image_process($file_path)
    {
        $md5 = md5($file_path);

        $query = Image::where('md5', $md5);

        if ($query->count() == 0) {
            $image = Image::create(['file_path' => $file_path, 'md5' => $md5]);
            return $image;
        } else {
            return $query->first();
        }
    }

}

modules/Gallery/Http/Controllers/Backend/Controller.php
<?php namespace Modules\Gallery\Http\Controllers\Backend;

use Pingpong\Modules\Routing\Controller as BaseController;

class Controller extends BaseController {

	public function __contruct()
	{
		$this->middleware('admin');
	}
	
}

modules/Gallery/Http/Controllers/Backend/ImagesController.php
<?php namespace Modules\Gallery\Http\Controllers\Backend;


class ImagesController extends Controller {

	public function __construct()
	{
		parent::__contruct();
	}


	public function index()
	{
		return view('Gallery::index');
	}


	
}

modules/Gallery/Http/Controllers/Backend/OrdersController.php
<?php namespace Modules\Gallery\Http\Controllers\Backend;

class OrdersController extends Controller {
	
	public function index()
	{
		return view('Gallery::index');
	}
	
}

modules/Gallery/Http/Controllers/Backend/PopularPhotosController.php
<?php namespace Modules\Gallery\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Modules\Gallery\Entities\PopularPhoto;
use Pingpong\Modules\Routing\Controller as BaseController;

class PopularPhotosController extends BaseController {


	public function __construct()
	{
		return $this->middleware('admin');
	}

	public function index()
	{
        $images = PopularPhoto::all();

		return mview('gallery::backend.popular_photos', compact('images'));
	}


    public function store(Request $request)
    {
        PopularPhoto::truncate();
        foreach($request->input('images') as $image){
            PopularPhoto::create(['file_path' => $image]);
        }
        return redirect()->back();
    }
	
}

modules/Gallery/Resources/views/backend/albums/attributes.blade.php
<div class="form-group">
    <label for="">{{ $attribute->name }}</label>
    <input type="text" class="form-control" name="attribute[][{{ $attribute->id }}]" value="">
</div>

modules/Gallery/Resources/views/backend/albums/confirm.blade.php
@extends('main')

@section('title', 'Xóa album '.$album->name)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['gallery.backend.albums.destroy', $album->id]]) !!}
    <!-- Panel _start -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5>Xác nhận xóa album</h5>
            @include('partials.backend.heading-elements')
        </div>
        <div class="panel-body">
            <div class="alert alert-danger">
                <strong>Cảnh báo !</strong> Bạn đang muốn xóa album <strong>[{{ $album->name }}]</strong>, việc này không thể phục hồi
            </div>

            {!! Form::submit('Vâng hãy xóa album này này !', ['class' => 'btn btn-danger']) !!}

            <a href="{{ route('gallery.backend.albums.index') }}" class="btn btn-success">
                <strong>Không, đưa tôi trở lại!</strong>
            </a>
        </div>
    </div>
    <!-- Panel End -->


   </form>
@endsection

modules/Gallery/Resources/views/backend/albums/index.blade.php
@extends('main')

@section('title', 'Quản lý album')

@section('breadcrumbs')
    {!! Breadcrumbs::render('gallery_album') !!}
@endsection

@section('functions')
    <a href="{{ route('gallery.backend.albums.create') }}" class="btn btn-link btn-float has-text"><i
                class="icon-plus2 text-primary"></i><span>{{ trans('gallery::album.add_label') }}</span></a>
    @endsection


    @section('content')
    {!! Form::open(['route' => 'gallery.backend.albums.bulk']) !!}
            <!-- Bulk Action -->
    <div class="bulk-action row">
        <div class="col-sm-4 col-md-3 col-lg-2">
            @include('partials.bulk-action')
        </div>
        <div class="col-sm-4 col-sm-offset-4 col-md-offset-6 col-lg-offset-8 col-md-3 col-lg-2">
            {!! $albums->render(null, 'pagination-xs pull-right') !!}
        </div>
    </div>
    <!-- Bulk Action End -->

    <!-- List Items Start -->
    <div class="panel panel-flat">
        <div class="panel-body no-padding">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th style="width: 50px"><input type="checkbox" class="styled top-check"></th>
                        <th>{{ trans('gallery::album.image') }}</th>
                        <th>{{ trans('gallery::album.name') }}</th>
                        <th>{{ trans('common.slug') }}</th>
                        <th>{{ trans('common.order_number') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($albums as $album)

                        <tr>
                            <td><input type="checkbox" class="styled item-checkbox" name="id[]"
                                       value="{{ $album->id }}"></td>
                            <td>
                                <a href="{{ route('gallery.backend.albums.edit', $album->id) }}">
                                    <img class="img-thumbnail" width="80"
                                         src="{{ ($album->thumbnail != '') ? $album->thumbnail : url('global/img/no_thumbnails.gif') }}" alt="">
                                </a>
                            </td>
                            <td>
                                <a href="{{ route('gallery.backend.albums.edit', $album->id) }}">{{ $album->name }}</a>
                            </td>
                            <td>{{ $album->slug }}</td>
                            <td>
                                <input type="text" class="text-center" value="{{ $album->order_number }}" style="width: 80px;">

                            </td>
                            <td>
                                <!-- edit button  -->
                                <a class="btn btn-xs btn-icon btn-default" data-popup="tooltip" title="Sửa album"
                                   data-placement="top"
                                   href="{{ route('gallery.backend.albums.edit', $album->id) }}">
                                    <i class="icon-pen"></i>
                                </a>
                                <!-- edit button  END-->

                                <!-- Delete  -->
                                <a class="btn btn-xs btn-icon btn-danger" data-popup="tooltip"
                                   title="{{ trans('gallery::album.delete') }}"
                                   data-placement="top"
                                   href="{{ route('gallery.backend.albums.confirm', $album->id) }}">
                                    <i class="icon-minus2"></i>
                                </a>
                                <!-- Delete  END-->

                                <!-- Delete  -->
                                <a class="btn btn-xs btn-icon btn-success" data-popup="tooltip"
                                   title="{{ trans('gallery::album.duplicate') }}"
                                   data-placement="top"
                                   href="{{ route('gallery.backend.albums.duplicate', $album->id) }}">
                                    <i class="icon-database-add"></i>
                                </a>
                                <!-- Delete  END-->

                                <!-- Preview  -->
                                <a target="_blank" class="btn btn-xs btn-icon btn-info" data-popup="tooltip"
                                   title="Xem trước"
                                   data-placement="top"
                                   href="{{ route('gallery.albums.show',$album->slug) }}">
                                    <i class="icon-eye2"></i>
                                </a>
                                <!-- Preview  END-->


                            </td>
                        </tr>
                    @endforeach


                    </tbody>

                </table>
            </div>
        </div>
    </div>

    <!-- Bulk Action -->
    <div class="bulk-action row">
        <div class="col-sm-4 col-md-3 col-lg-2">
            @include('partials.bulk-action')
        </div>
        <div class="col-sm-4 col-sm-offset-4 col-md-offset-6 col-lg-offset-8 col-md-3 col-lg-2">
            {!! $albums->render(null, 'pagination-xs pull-right') !!}
        </div>
    </div>
    <!-- Bulk Action End -->

    <!-- List Items End -->
    {!! Form::close() !!}
@endsection

modules/Gallery/Resources/views/backend/albums/manage-attributes.blade.php
<div class="form-group">
    <div class="input-group">
        <select id="add-attribute" class="form-control">
            @foreach($attributeGroups as $group)
                <optgroup label="{{ $group->name }}">
                    @foreach($group->attributes()->get() as $attribute)
                        <option value="{{ $attribute->id }}">{{ $attribute->name }}</option>
                    @endforeach
                </optgroup>
            @endforeach
        </select>

        <div class="input-group-btn">
            <button type="button" class="btn btn-info" id="btn-add-attribute">Thêm thuộc tính</button>
        </div>
    </div>
</div>
<!-- Attribute Container -->
<div class="attributes-container">

</div>
<!-- Attribute Container End -->

modules/Gallery/Resources/views/backend/albums/manage-options.blade.php
<!-- Options Container -->
<div class="options-container">

    @if(! $product->exists || $product->options()->count() == 0)
        <div class="row">
            <div class="col-xs-3"> <!-- required for floating -->
                <!-- Nav tabs -->
                <ul class="nav nav-tabs tabs-left">
                    @foreach(options() as $i => $option)
                        <li class="{{ ($i == 0) ? 'active' : '' }}"><a href="#option-{{ $option->id }}"
                                                                       data-toggle="tab">{{ $option->name }}</a></li>
                    @endforeach
                </ul>
            </div>

            <div class="col-xs-9">
                <!-- Tab panes -->
                <div class="tab-content">
                    @foreach(options() as $i => $option)
                        <div class="tab-pane {{ ($i == 0) ? 'active' : '' }}" id="option-{{ $option->id }}">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Lựa chọn</th>
                                    <th width="100">Số lượng</th>
                                    <th>Giá</th>
                                    <th width="50">
                                        <button data-option-id="{{ $option->id }}" type="button"
                                                class="btn btn-xs btn-success add-option-value"><i
                                                    class="icon-plus3"></i></button>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <!-- End row -->
    @else
        <div class="row">
            <div class="col-xs-3"> <!-- required for floating -->
                <!-- Nav tabs -->
                <ul class="nav nav-tabs tabs-left">
                    @foreach(options() as $i => $option)
                        <li class="{{ ($i == 0) ? 'active' : '' }}"><a href="#option-{{ $option->id }}"
                                                                       data-toggle="tab">{{ $option->name }}</a></li>
                    @endforeach
                </ul>
            </div>

            <div class="col-xs-9">
                <!-- Tab panes -->
                <div class="tab-content">
                    @foreach(options() as $i => $option)
                        <div class="tab-pane {{ ($i == 0) ? 'active' : '' }}" id="option-{{ $option->id }}">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Lựa chọn</th>
                                    <th width="100">Số lượng</th>
                                    <th>Giá</th>
                                    <th width="50">
                                        <button data-option-id="{{ $option->id }}" type="button"
                                                class="btn btn-xs btn-success add-option-value"><i
                                                    class="icon-plus3"></i></button>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($product->options()->get() as $n => $option_item)
                                    @if($option_item->id == $option->id)
                                        <tr>

                                            <!-- Name -->
                                            <td>{!! Form::select(
                                                'option_value['.$option->id.']['.$n.'][option_value_id]',
                                                $option->values()->lists('name', 'id') ,
                                                $option_item->pivot->option_value_id,
                                                ['class' => 'form-control'])
                                            !!}</td>
                                            <!-- End Name -->

                                            <!-- Quantity -->
                                            <td>{!! Form::text(
                                            'option_value['.$option->id.']['.$n.'][quantity]',
                                            $option_item->pivot->quantity,
                                            ['class' => 'form-control'])
                                            !!}</td>
                                            <!-- End Quantity -->


                                            <td>
                                                <!-- Price Prefix -->
                                                {!! Form::select(
                                                'option_value['.$option->id.']['.$n.'][price_prefix]',
                                                config('app.options_prefix'),
                                                $option_item->pivot->price_prefix,
                                                ['class' => 'form-control'])
                                                !!}
                                                        <!-- End Price Prefix -->

                                                <!-- Price -->
                                                {!! Form::text(
                                                'option_value['.$option->id.']['.$n.'][price]',
                                                $option_item->pivot->price,
                                                ['class' => 'form-control']) !!}
                                                        <!-- End Price -->
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-xs btn-danger btn-detach-option"
                                                        data-option-id="{{ $option->id }}"
                                                        data-product-id="{{ $product->id }}">
                                                    <i class="icon-minus2"></i></button>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <!-- End row -->
    @endif
    <p>Lưu ý: Hệ thống chưa phát triển quản lý kho, bạn có thể bỏ trống trường số lượng</p>
</div><!-- Options Container End -->