app/Http/routes.php
<?php
Route::get('blog.html', 'BlogController@index');
Route::get('san-pham.html', function(){
    return view('products.index');
});
Route::get('san-pham/chi-tiet.html', function(){
    return view('products.show');
});

Route::get('tin-tuc.html', function(){
    return view('blog/index');
});

Route::get('tin-tuc/chi-tiet.html', function(){
    return view('blog/show');
});

Route::get('trang', function(){
    return view('page-default');
});


Route::get('sitemap.xml', ['as' => 'sitemap.xml', 'uses' => 'ToolsController@sitemap']);

//Backend-----------------------------------------------------------------------------------------------------------
Route::controller('auth/password', 'Auth\PasswordController', [
    'getEmail' => 'auth.password.email',
    'getReset' => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'getLogout' => 'auth.logout'
]);

//Advertising
Route::resource('backend/ads', 'Backend\AdsController', ['except' => ['show', 'create']]);
Route::post('backend/ads/bulk', ['as' => 'backend.ads.bulk', 'uses' => 'Backend\AdsController@bulk']);
Route::get('backend/ads/{id}/duplicate', ['as' => 'backend.ads.duplicate', 'uses' => 'Backend\AdsController@duplicate']);
Route::get('backend/ads/{id}/confirm', ['as' => 'backend.ads.confirm', 'uses' => 'Backend\AdsController@confirm']);

Route::get('blogcategories/{categories}/confirm', ['as' => 'backend.blogcategories.confirm', 'uses' => 'Backend\BlogCategoriesController@confirm']);
Route::post('backend/blogcategories/bulk', ['as' => 'backend.blogcategories.bulk', 'uses' => 'Backend\BlogCategoriesController@index']);
Route::resource('backend/blogcategories', 'Backend\BlogCategoriesController', ['except' => ['show']]);
Route::get('backend/productcategories/{categories}/confirm', ['as' => 'backend.productcategories.confirm', 'uses' => 'Backend\ProductCategoriesController@confirm']);
Route::resource('backend/productcategories', 'Backend\ProductCategoriesController', ['except' => ['show']]);
Route::resource('backend/messages', 'Backend\MessagesController', ['except' => ['show']]);
Route::get('backend/messages/{id}/mark-read', ['as' => 'backend.messages.markread', 'uses' => 'Backend\MessagesController@markRead']);
Route::get('backend/messages/{id}/delete', ['as' => 'backend.messages.delete', 'uses' => 'Backend\MessagesController@delete']);
//Menu
Route::get('backend/menus/{id}/confirm', ['as' => 'backend.menus.confirm', 'uses' => 'Backend\MenusController@confirm']);
Route::post('backend/menus/additem', ['as' => 'backend.menus.additem', 'uses' => 'Backend\MenusController@addItem']);
Route::post('backend/menus/save', ['as' => 'backend.menus.save', 'uses' => 'Backend\MenusController@saveMenu']);
Route::post('backend/menus/order', ['as' => 'backend.menus.order', 'uses' => 'Backend\MenusController@order']);
Route::get('backend/menus/{id}/remove', ['as' => 'backend.menus.remove', 'uses' => 'Backend\MenusController@remove']);
Route::resource('backend/menus', 'Backend\MenusController', ['except' => ['show']]);

Route::get('backend/themeoption', ['as' => 'backend.themeoption.index', 'uses' => 'Backend\ThemeOptionController@index']);
Route::post('backend/themeoption/save', ['as' => 'backend.themeoption.save', 'uses' => 'Backend\ThemeOptionController@save']);
Route::resource('backend/products', 'Backend\ProductsController');
Route::get('product/detach-image/{image_id}/{product_id}', 'Backend\ProductsController@detachImage');
Route::get('product/detach-option/{option_id}/{product_id}/{option_value_id}', 'Backend\ProductsController@detachOption');
Route::get('product/add-option/{type}/{length}', 'Backend\ProductsController@addOptionAjax');
Route::resource('backend/orders', 'Backend\OrdersController');
Route::get('backend/order/{id}/update_status/{status_id}', ['as' => 'backend.order.update_status', 'uses' => 'Backend\OrdersController@update_status']);
//File manager
Route::resource('backend/filemanager', 'Backend\FileManagerController');
Route::post('backend/get_subdirectories',  'Backend\FileManagerController@get_subdirectories');
Route::get('backend/orders/{id}/confirm', ['as' => 'backend.orders.confirm', 'uses' => 'Backend\OrdersController@confirm']);
Route::get('backend/attributegroups/{id}/confirm', ['as' => 'backend.attributegroups.confirm', 'uses' => 'Backend\AttributeGroupsController@confirm']);
Route::get('backend/attributes/{id}/confirm', ['as' => 'backend.attributes.confirm', 'uses' => 'Backend\AttributesController@confirm']);
Route::resource('backend/attributegroups', 'Backend\AttributeGroupsController');
Route::resource('backend/attributes', 'Backend\AttributesController');

Route::get('admin', ['as' => 'admin', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend', ['as' => 'backend', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/dashboard', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/products/{product}/confirm', ['as' => 'backend.products.confirm', 'uses' => 'Backend\ProductsController@confirm']);
Route::get('/home', function(){
   return view('backend');
});
Route::resource('backend/setting', 'Backend\SettingsController');
Route::resource('backend/branch', 'Backend\BranchesController');

//FrontEnd
Route::get('file/get/{filename}', [
    'as' => 'getentry', 'uses' => 'FilesController@get']);

Route::get('image/products/{id}/{slug}.jpg', [
    'as' => 'product_img', 'uses' => 'FilesController@get_product_image']);


Route::get('/', 'HomeController@index');






//FrontEnd

Route::post('product/order/place-order', ['as' => 'order.place', 'uses' => 'ProductsController@placeOrder']);
Route::post('product/review', ['as' => 'product.review', 'uses' => 'ProductsController@review']);
Route::post('product/update-price',  'ProductsController@updateShowPagePrice');
Route::get('tool/slug/genslug/{string}', 'ToolsController@genSlug');
Route::get('getattributehtml/{id}', 'ToolsController@getAttributeHtml');
Route::post('render-new-product-image', 'ToolsController@renderNewProductImage');
Route::get('getoptionvalue/{id}', 'ToolsController@getOptionValue');
Route::get('get-district/{province_id}', 'ToolsController@getDistrict');
Route::get('selected-ship-to-different-address', 'ToolsController@toggleShippingAddress');
Route::get('get-ward/{district_id}', 'ToolsController@getWard');
Route::get('apply-coupon/{code}', 'HomeController@applyCoupon');

Route::get('create-admin-role', 'ToolsController@createrole');

Route::get('session', function(){
    dd(session());
});

Route::resource('user', 'UsersController', ['except' => ['create', 'destroy', 'show', 'index']]);

Route::get('login.html', [
    'as' => 'users.login', 'uses' => 'UsersController@login']);

Route::get('register.html', [
    'as' => 'users.register', 'uses' => 'UsersController@register']);

Route::get('profile.html', [
    'as' => 'user.profile', 'uses' => 'UsersController@profile']);

Route::post('postlogin', [
    'as' => 'user.login.post', 'uses' => 'UsersController@postLogin']);
Route::get('postregister', [
    'as' => 'user.register.post', 'uses' => 'UsersController@postRegister']);


Route::get('tags/product/{slug}.{id}.html', ['as' => 'product.tag', 'uses' => 'ProductsController@tag']);
Route::get('user/github/login', ['as' => 'user.github.login', 'uses' => 'UsersController@githubLogin']);
Route::get('user/facebook/login', ['as' => 'user.facebook.login', 'uses' => 'UsersController@facebookLogin']);
Route::get('user/facebook/login/step/2', ['as' => 'user.facebook.login.step2', 'uses' => 'UsersController@facebookLoginStep2']);
Route::get('user/google/login', ['as' => 'user.google.login', 'uses' => 'UsersController@googleLogin']);
Route::get('user/google/login/step/2', ['as' => 'user.google.login.step2', 'uses' => 'UsersController@googleLoginStep2']);
Route::get('user/twitter/login', ['as' => 'user.twitter.login', 'uses' => 'UsersController@twitterLogin']);
Route::get('user/twitter/login/step/2', ['as' => 'user.twitter.login.step2', 'uses' => 'UsersController@twitterLoginStep2']);

Route::get('cart/information', function(){
   return view('cart.information');
});


//Product
//Product-Frontend
Route::get('product/dat-hang-thanh-cong.html', ['as' => 'product.ordersuccess', 'uses' => 'ProductsController@orderSuccess']);

Route::get('product/checkout', ['as' => 'product.checkout', 'uses' => 'ProductsController@checkout']);
Route::resource('product', 'ProductsController');
Route::get('product.html', ['as' => 'product', 'uses' => 'ProductsController@index']);

Route::post('product/add-to-cart', ['as' => 'cart.add', 'uses' => 'CartController@add']);
Route::get('cart/view-cart', ['as' => 'cart.show', 'uses' => 'CartController@show']);
Route::get('cart/clear', ['as' => 'cart.clear', 'uses' => 'CartController@clear']);
Route::get('cart/delete/{key}', ['as' => 'cart.delete', 'uses' => 'CartController@delete']);
Route::get('cart/delete/ajax/{key}', ['as' => 'cart.ajax.delete', 'uses' => 'CartController@deleteAjax']);
Route::get('cart/update/{key}/{quantity}', ['as' => 'cart.update', 'uses' => 'CartController@update']);
Route::get('product/{id}-{slug}.html', ['as' => 'product.show', 'uses' => 'ProductsController@show']);
//Product--Backend
Route::post('backend/products/bulk', ['as' => 'backend.products.bulk', 'uses' => 'Backend\ProductsController@index']);
Route::get('backend/options/{options}/confirm', ['as' => 'backend.options.confirm', 'uses' => 'Backend\OptionsController@confirm']);
Route::post('backend/options/bulk', ['as' => 'backend.options.bulk', 'uses' => 'Backend\OptionsController@index']);
Route::resource('backend/options', 'Backend\OptionsController');
Route::get('backend/coupons/{id}/confirm', ['as' => 'backend.coupons.confirm', 'uses' => 'Backend\CouponsController@confirm']);
Route::post('backend/coupons/bulk', ['as' => 'backend.coupons.bulk', 'uses' => 'Backend\CouponsController@index']);

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Advertising;
use App\Http\Requests;


class AdsController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param Ads $ads
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Advertising $ads)
    {
        $list_ads = Advertising::paginate(15);

        return view('backend.ads.index', compact('ads', 'list_ads'));
    }


    /**
     * Xóa hàng loạt
     *
     * @param Request $request
     * @param Advertising $ads
     * @return \Illuminate\Http\RedirectResponse
     */
    public function bulk(Request $request, Advertising $ads)
    {
        bulk_delete($request, $ads);

        return redirect(route('backend.ads.index'));
    }

    /**
     * Lưu quảng cáo
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        //Validate
        $this->validate($request, [
            'name' => 'required|max:255',
            'slug' => 'required|max:255|unique:advertisings,slug',
            'description' => 'max:255',
            'image' => 'required|max:255',
            'link' => 'required|max:255'
        ]);

        //Tạo quảng cáo
        $ads = Advertising::create($request->all());

        //thoát
        flash()->success(trans('common.success'), trans('ads.create_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));

    }


    /**
     * Form edit quảng cáo
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        //Lấy ra quảng cáo
        $ads = Advertising::findOrFail($id);

        //Danh sách tất cả ads
        $list_ads = Advertising::paginate(15);

        return view('backend.ads.index', compact('ads', 'list_ads'));
    }


    /**
     * Cập nhật quảng cáo
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        //Validate
        $this->validate($request, [
            'name' => 'required|max:255',
            'slug' => 'required|max:255',
            'description' => 'max:255',
            'image' => 'required|max:255',
            'link' => 'required|max:255'
        ]);

        //Tìm quảng cáo cần chỉnh sửa
        $ads = Advertising::findOrFail($id);

        //Kiểm tra xem slug có trùng các quảng cáo khác hay không
        if(Advertising::where('slug', $ads->slug)->where('id', '!=', $ads->id)->count() > 0){
            flash(trans('common.slug_duplicate'));
            return redirect()->back();
        }

        //Tạo quảng cáo
        $ads->update($request->all());

        //thoát
        flash()->success(trans('common.success'), trans('ads.update_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));

    }


    /**
     * Nhân đôi quảng cáo
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function duplicate($id)
    {
        //Lấy ra quảng cáo cần nhân đôi
        $ads = Advertising::findOrFail($id)->toArray();

        //Thay đổi slug
        $ads['slug'] = $ads['slug'] . '_';

        //Tạo mới
        $ads = Advertising::create($ads);

        flash(trans('ads.duplicate_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.edit',$ads->id));
    }


    /**
     * Xác nhận xóa quảng cáo
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm($id)
    {
        //Lấy ra quảng cáo cần xóa
        $ads = Advertising::findOrFail($id);

        return view('backend.ads.confirm', compact('ads'));
    }


    /**
     * Xóa quảng cáo
     *
     * @param $id
     */
    public function destroy($id)
    {
        //Lấy ra quảng cáo cần xóa
        $ads = Advertising::findOrFail($id);

        //Xóa
        $ads->delete();

        flash()->success(trans('common.success'), trans('ads.delete_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));
    }
}

app/Http/Controllers/Backend/AdsPositionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Advertising;
use App\Models\AdvertisingPosition;
use App\Http\Requests;

class AdsPositionController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ads_positions = AdvertisingPosition::paginate(15);

        return view('backend.ads_positions.index', compact('ads_position'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required',
            'slug'  => 'required',
        ]);

        AdvertisingPosition::create($request->all());

        flash()->success('Tạo vị trí quảng cáo thành công');

        return redirect(route('backend.adsposition.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use App\View\ThemeViewFinder;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Request;

abstract class Controller extends BaseController
{

    use ValidatesRequests;


    public function __construct()
    {
        $this->middleware('admin');
        if (session_id() == '') {
            @session_start();
            /* or Session:start(); */
        }
        $_SESSION['isLoggedIn'] = auth()->check() ? true : false;

    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php
/**
 * Created by PhpStorm.
 * User: Rain
* Date: 09/01/2016
* Time: 6:12 PM
*/

namespace App\Http\Controllers\Backend;

use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        return redirect(route('gallery.backend.albums.index'));

        $name = Route::getCurrentRoute()->getPath();
        return view('dashboard');
    }
}

resources/views/partials/backend/appscript.blade.php
@section('themejs')
    <script type="text/javascript" src="{{ url('assets') }}/js/core/app.js"></script>
@endsection

resources/views/partials/backend/footer.blade.php
<div class="footer text-muted">
    &copy; 2015. <a href="http://cloud.cass.vn">Cloudcass CMS & eCommerce System</a> by <a href="http://cass.vn" target="_blank">Duy Kiều</a>
    <p>Sản phẩm đã được đăng ký tại Cục sở hữu trí tuệ. Mọi vi phạm bản quyền đều bị xử lý theo pháp luật.</p>
</div>

resources/views/partials/backend/heading-elements.blade.php
<div class="heading-elements">
    <ul class="icons-list">
        <li><a data-action="collapse"></a></li>
        <li><a data-action="reload"></a></li>
        <li><a data-action="close"></a></li>
    </ul>
</div>

resources/views/partials/backend/metadata.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@yield('title') &mdash; Premeumlens</title>
<base href="{{ url() }}">
<!-- Global stylesheets -->
<link href="{{ url('assets') }}/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
<link href="{{ url('assets') }}/css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="{{ url('assets') }}/css/core.css" rel="stylesheet" type="text/css">
<link href="{{ url('assets') }}/css/components.css" rel="stylesheet" type="text/css">
<link href="{{ url('assets') }}/css/colors.css" rel="stylesheet" type="text/css">
<link href="{{ url('assets') }}/css/custom.css" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->

<!-- Core JS files -->


<script type="text/javascript" src="{{ url('assets') }}/js/plugins/loaders/pace.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/core/libraries/jquery.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/core/libraries/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/plugins/loaders/blockui.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/plugins/forms/styling/uniform.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/pages/form_checkboxes_radios.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/plugins/forms/selects/bootstrap_select.min.js"></script>
<script type="text/javascript" src="{{ url('assets') }}/js/pages/components_popups.js"></script>
<script type="text/javascript" src="{{ url('global') }}/js/address.js"></script>

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>
<!-- /core JS files -->

resources/views/partials/backend/navbar.blade.php
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ url() }}" target="_blank"><img src="{{url('assets')}}/images/logo_light.png" alt=""></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

        <p class="navbar-text"><span class="label bg-success-400">Online</span></p>

        <ul class="nav navbar-nav navbar-right">


            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{url('assets')}}/images/demo/users/face11.jpg" alt=""> <span>{{ auth()->user()->name }}</span>
                    <i class="caret"></i> </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-user-plus"></i> Tài khoản của tôi</a></li>
                    <li><a href="{{ route('auth.logout') }}"><i class="icon-switch2"></i> Thoát</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

resources/views/partials/backend/sidebar.blade.php
<div class="sidebar sidebar-main">
    <div class="sidebar-content">

        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    <!-- Main -->
                    <li class="navigation-header"><span>Nội dung</span> <i class="icon-menu" title="Main pages"></i>
                    </li>
                    <li class="{{set_active('backend/posts') . set_active('backend/posts/create') . set_active('backend/posts/edit') . set_active('backend/posts/index')}}">
                        <a href="#"><i class="icon-stack"></i> <span>Nội dung</span></a>
                        <ul>
                            <li><a href="{{ route('backend.posts.index') }}">Tất cả bài viết</a></li>
                            <li><a href="{{ route('backend.posts.create') }}">Thêm bài viết</a></li>
                            <li><a href="{{ route('backend.blogcategories.index') }}">Danh mục</a></li>
                            {{--<li><a href="">Tags</a></li>--}}
                        </ul>
                    </li>
                    <li class="{{set_active('backend/pages') . set_active('backend/pages/create') . set_active('backend/pages/edit') . set_active('backend/pages/index')}}">
                        <a href="#"><i class="icon-copy"></i> <span>Trang</span></a>
                        <ul>
                            <li><a href="{{ route('backend.pages.index') }}">Tất cả trang</a></li>
                            <li><a href="{{ route('backend.pages.create') }}">Thêm trang mới</a></li>
                        </ul>
                    </li>
                    <li class="{{ set_active('backend/users') }}">
                        <a href="{{ route('backend.users.index') }}"><i class="icon-user"></i>
                            <span>Người dùng</span></a>
                    </li>


                    <!-- Giao diện -->
                    <li class="navigation-header"><span>Giao diện</span> <i class="icon-menu" title="Giao diện"></i>
                    </li>

                    <li class="">
                        <a href="{{ route('backend.menus.index') }}"><i class="icon-paragraph-justify3"></i>
                            <span>Trình đơn</span></a>
                    </li>
                    <li class="">
                        <a href="{{ route('backend.ads.index') }}"><i class="icon-bookmark"></i>
                            <span>Quảng cáo</span></a>
                    </li>

                    <!-- End Giao diện -->

                    @if(count(config('modules.menu') > 0))
                        @foreach(config('modules.menu') as $menu)
                            @if($menu['head'])
                                <li class="navigation-header"><span>{{ $menu['head_title'] }}</span> <i
                                            class="icon-menu" title="{{ $menu['head_title'] }}"></i>
                                </li>
                            @endif
                            @foreach($menu['items'] as $item)
                                @if($item['sub'])
                                    <li class="">
                                        <a href="#"><i class="icon-list-ordered"></i>
                                            <span>{{ $item['items'][0]['name'] }}</span></a>
                                        <ul>
                                            @foreach($item['items'] as $key => $sub_item)
                                                <li class="">
                                                    <a href="{{ route($sub_item['route']) }}">
                                                        <span>{{ ($key == 0) ? 'Tất cả' : '' }} {{ $sub_item['name'] }}</span></a>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </li>

                                @else
                                    @foreach($item['items'] as $sub_item)
                                        <li class="">
                                            <a href="{{ route($sub_item['route']) }}"><i class="icon-list-ordered"></i>
                                                <span>{{ $sub_item['name'] }}</span></a>
                                        </li>
                                        @endforeach
                                        @endif

                                        @endforeach
                                        @endforeach
                                        @endif


                                                <!-- Forms -->
                                        <li class="navigation-header"><span>Công cụ</span> <i class="icon-menu"
                                                                                              title="Forms"></i></li>
                                        <li class=="{{ set_active('backend/settings') }}">
                                            <a href="{{ route('backend.setting.index') }}"><i class="icon-user"></i>
                                                <span>Cài đặt</span></a>
                                        </li>

                                        <!-- /forms -->


                </ul>
            </div>
        </div>
        <!-- /main navigation -->

    </div>
</div>