app/Http/routes.php
<?php
Route::get('blog.html', 'BlogController@index');
Route::get('san-pham.html', function(){
    return view('products.index');
});
Route::get('san-pham/chi-tiet.html', function(){
    return view('products.show');
});

Route::get('tin-tuc.html', function(){
    return view('blog/index');
});

Route::get('tin-tuc/chi-tiet.html', function(){
    return view('blog/show');
});

Route::get('trang', function(){
    return view('page-default');
});


Route::get('sitemap.xml', ['as' => 'sitemap.xml', 'uses' => 'ToolsController@sitemap']);

//Backend-----------------------------------------------------------------------------------------------------------
Route::controller('auth/password', 'Auth\PasswordController', [
    'getEmail' => 'auth.password.email',
    'getReset' => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'getLogout' => 'auth.logout'
]);

//Advertising
Route::resource('backend/ads', 'Backend\AdsController', ['except' => ['show', 'create']]);
Route::post('backend/ads/bulk', ['as' => 'backend.ads.bulk', 'uses' => 'Backend\AdsController@bulk']);
Route::get('backend/ads/{id}/duplicate', ['as' => 'backend.ads.duplicate', 'uses' => 'Backend\AdsController@duplicate']);
Route::get('backend/ads/{id}/confirm', ['as' => 'backend.ads.confirm', 'uses' => 'Backend\AdsController@confirm']);

Route::get('blogcategories/{categories}/confirm', ['as' => 'backend.blogcategories.confirm', 'uses' => 'Backend\BlogCategoriesController@confirm']);
Route::post('backend/blogcategories/bulk', ['as' => 'backend.blogcategories.bulk', 'uses' => 'Backend\BlogCategoriesController@index']);
Route::resource('backend/blogcategories', 'Backend\BlogCategoriesController', ['except' => ['show']]);
Route::get('backend/productcategories/{categories}/confirm', ['as' => 'backend.productcategories.confirm', 'uses' => 'Backend\ProductCategoriesController@confirm']);
Route::resource('backend/productcategories', 'Backend\ProductCategoriesController', ['except' => ['show']]);
Route::resource('backend/messages', 'Backend\MessagesController', ['except' => ['show']]);
Route::get('backend/messages/{id}/mark-read', ['as' => 'backend.messages.markread', 'uses' => 'Backend\MessagesController@markRead']);
Route::get('backend/messages/{id}/delete', ['as' => 'backend.messages.delete', 'uses' => 'Backend\MessagesController@delete']);
//Menu
Route::get('backend/menus/{id}/confirm', ['as' => 'backend.menus.confirm', 'uses' => 'Backend\MenusController@confirm']);
Route::post('backend/menus/additem', ['as' => 'backend.menus.additem', 'uses' => 'Backend\MenusController@addItem']);
Route::post('backend/menus/save', ['as' => 'backend.menus.save', 'uses' => 'Backend\MenusController@saveMenu']);
Route::post('backend/menus/order', ['as' => 'backend.menus.order', 'uses' => 'Backend\MenusController@order']);
Route::get('backend/menus/{id}/remove', ['as' => 'backend.menus.remove', 'uses' => 'Backend\MenusController@remove']);
Route::resource('backend/menus', 'Backend\MenusController', ['except' => ['show']]);

Route::get('backend/themeoption', ['as' => 'backend.themeoption.index', 'uses' => 'Backend\ThemeOptionController@index']);
Route::post('backend/themeoption/save', ['as' => 'backend.themeoption.save', 'uses' => 'Backend\ThemeOptionController@save']);
Route::resource('backend/products', 'Backend\ProductsController');
Route::get('product/detach-image/{image_id}/{product_id}', 'Backend\ProductsController@detachImage');
Route::get('product/detach-option/{option_id}/{product_id}/{option_value_id}', 'Backend\ProductsController@detachOption');
Route::get('product/add-option/{type}/{length}', 'Backend\ProductsController@addOptionAjax');
Route::resource('backend/orders', 'Backend\OrdersController');
Route::get('backend/order/{id}/update_status/{status_id}', ['as' => 'backend.order.update_status', 'uses' => 'Backend\OrdersController@update_status']);
//File manager
Route::resource('backend/filemanager', 'Backend\FileManagerController');
Route::post('backend/get_subdirectories',  'Backend\FileManagerController@get_subdirectories');
Route::get('backend/orders/{id}/confirm', ['as' => 'backend.orders.confirm', 'uses' => 'Backend\OrdersController@confirm']);
Route::get('backend/attributegroups/{id}/confirm', ['as' => 'backend.attributegroups.confirm', 'uses' => 'Backend\AttributeGroupsController@confirm']);
Route::get('backend/attributes/{id}/confirm', ['as' => 'backend.attributes.confirm', 'uses' => 'Backend\AttributesController@confirm']);
Route::resource('backend/attributegroups', 'Backend\AttributeGroupsController');
Route::resource('backend/attributes', 'Backend\AttributesController');

Route::get('admin', ['as' => 'admin', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend', ['as' => 'backend', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/dashboard', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);
Route::get('backend/products/{product}/confirm', ['as' => 'backend.products.confirm', 'uses' => 'Backend\ProductsController@confirm']);
Route::get('/home', function(){
   return view('backend');
});
Route::resource('backend/setting', 'Backend\SettingsController');
Route::resource('backend/branch', 'Backend\BranchesController');

//FrontEnd
Route::get('file/get/{filename}', [
    'as' => 'getentry', 'uses' => 'FilesController@get']);

Route::get('image/products/{id}/{slug}.jpg', [
    'as' => 'product_img', 'uses' => 'FilesController@get_product_image']);


Route::get('/', 'HomeController@index');






//FrontEnd

Route::post('product/order/place-order', ['as' => 'order.place', 'uses' => 'ProductsController@placeOrder']);
Route::post('product/review', ['as' => 'product.review', 'uses' => 'ProductsController@review']);
Route::post('product/update-price',  'ProductsController@updateShowPagePrice');
Route::get('tool/slug/genslug/{string}', 'ToolsController@genSlug');
Route::get('getattributehtml/{id}', 'ToolsController@getAttributeHtml');
Route::post('render-new-product-image', 'ToolsController@renderNewProductImage');
Route::get('getoptionvalue/{id}', 'ToolsController@getOptionValue');
Route::get('get-district/{province_id}', 'ToolsController@getDistrict');
Route::get('selected-ship-to-different-address', 'ToolsController@toggleShippingAddress');
Route::get('get-ward/{district_id}', 'ToolsController@getWard');
Route::get('apply-coupon/{code}', 'HomeController@applyCoupon');

Route::get('create-admin-role', 'ToolsController@createrole');

Route::get('session', function(){
    dd(session());
});

Route::resource('user', 'UsersController', ['except' => ['create', 'destroy', 'show', 'index']]);

Route::get('login.html', [
    'as' => 'users.login', 'uses' => 'UsersController@login']);

Route::get('register.html', [
    'as' => 'users.register', 'uses' => 'UsersController@register']);

Route::get('profile.html', [
    'as' => 'user.profile', 'uses' => 'UsersController@profile']);

Route::post('postlogin', [
    'as' => 'user.login.post', 'uses' => 'UsersController@postLogin']);
Route::get('postregister', [
    'as' => 'user.register.post', 'uses' => 'UsersController@postRegister']);


Route::get('tags/product/{slug}.{id}.html', ['as' => 'product.tag', 'uses' => 'ProductsController@tag']);
Route::get('user/github/login', ['as' => 'user.github.login', 'uses' => 'UsersController@githubLogin']);
Route::get('user/facebook/login', ['as' => 'user.facebook.login', 'uses' => 'UsersController@facebookLogin']);
Route::get('user/facebook/login/step/2', ['as' => 'user.facebook.login.step2', 'uses' => 'UsersController@facebookLoginStep2']);
Route::get('user/google/login', ['as' => 'user.google.login', 'uses' => 'UsersController@googleLogin']);
Route::get('user/google/login/step/2', ['as' => 'user.google.login.step2', 'uses' => 'UsersController@googleLoginStep2']);
Route::get('user/twitter/login', ['as' => 'user.twitter.login', 'uses' => 'UsersController@twitterLogin']);
Route::get('user/twitter/login/step/2', ['as' => 'user.twitter.login.step2', 'uses' => 'UsersController@twitterLoginStep2']);

Route::get('cart/information', function(){
   return view('cart.information');
});


//Product
//Product-Frontend
Route::get('product/dat-hang-thanh-cong.html', ['as' => 'product.ordersuccess', 'uses' => 'ProductsController@orderSuccess']);

Route::get('product/checkout', ['as' => 'product.checkout', 'uses' => 'ProductsController@checkout']);
Route::resource('product', 'ProductsController');
Route::get('product.html', ['as' => 'product', 'uses' => 'ProductsController@index']);

Route::post('product/add-to-cart', ['as' => 'cart.add', 'uses' => 'CartController@add']);
Route::get('cart/view-cart', ['as' => 'cart.show', 'uses' => 'CartController@show']);
Route::get('cart/clear', ['as' => 'cart.clear', 'uses' => 'CartController@clear']);
Route::get('cart/delete/{key}', ['as' => 'cart.delete', 'uses' => 'CartController@delete']);
Route::get('cart/delete/ajax/{key}', ['as' => 'cart.ajax.delete', 'uses' => 'CartController@deleteAjax']);
Route::get('cart/update/{key}/{quantity}', ['as' => 'cart.update', 'uses' => 'CartController@update']);
Route::get('product/{id}-{slug}.html', ['as' => 'product.show', 'uses' => 'ProductsController@show']);
//Product--Backend
Route::post('backend/products/bulk', ['as' => 'backend.products.bulk', 'uses' => 'Backend\ProductsController@index']);
Route::get('backend/options/{options}/confirm', ['as' => 'backend.options.confirm', 'uses' => 'Backend\OptionsController@confirm']);
Route::post('backend/options/bulk', ['as' => 'backend.options.bulk', 'uses' => 'Backend\OptionsController@index']);
Route::resource('backend/options', 'Backend\OptionsController');
Route::get('backend/coupons/{id}/confirm', ['as' => 'backend.coupons.confirm', 'uses' => 'Backend\CouponsController@confirm']);
Route::post('backend/coupons/bulk', ['as' => 'backend.coupons.bulk', 'uses' => 'Backend\CouponsController@index']);

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Advertising;
use App\Http\Requests;


class AdsController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param Ads $ads
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Advertising $ads)
    {
        $list_ads = Advertising::paginate(15);

        return view('backend.ads.index', compact('ads', 'list_ads'));
    }


    /**
     * Xóa hàng loạt
     *
     * @param Request $request
     * @param Advertising $ads
     * @return \Illuminate\Http\RedirectResponse
     */
    public function bulk(Request $request, Advertising $ads)
    {
        bulk_delete($request, $ads);

        return redirect(route('backend.ads.index'));
    }

    /**
     * Lưu quảng cáo
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        //Validate
        $this->validate($request, [
            'name' => 'required|max:255',
            'slug' => 'required|max:255|unique:advertisings,slug',
            'description' => 'max:255',
            'image' => 'required|max:255',
            'link' => 'required|max:255'
        ]);

        //Tạo quảng cáo
        $ads = Advertising::create($request->all());

        //thoát
        flash()->success(trans('common.success'), trans('ads.create_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));

    }


    /**
     * Form edit quảng cáo
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        //Lấy ra quảng cáo
        $ads = Advertising::findOrFail($id);

        //Danh sách tất cả ads
        $list_ads = Advertising::paginate(15);

        return view('backend.ads.index', compact('ads', 'list_ads'));
    }


    /**
     * Cập nhật quảng cáo
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        //Validate
        $this->validate($request, [
            'name' => 'required|max:255',
            'slug' => 'required|max:255',
            'description' => 'max:255',
            'image' => 'required|max:255',
            'link' => 'required|max:255'
        ]);

        //Tìm quảng cáo cần chỉnh sửa
        $ads = Advertising::findOrFail($id);

        //Kiểm tra xem slug có trùng các quảng cáo khác hay không
        if(Advertising::where('slug', $ads->slug)->where('id', '!=', $ads->id)->count() > 0){
            flash(trans('common.slug_duplicate'));
            return redirect()->back();
        }

        //Tạo quảng cáo
        $ads->update($request->all());

        //thoát
        flash()->success(trans('common.success'), trans('ads.update_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));

    }


    /**
     * Nhân đôi quảng cáo
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function duplicate($id)
    {
        //Lấy ra quảng cáo cần nhân đôi
        $ads = Advertising::findOrFail($id)->toArray();

        //Thay đổi slug
        $ads['slug'] = $ads['slug'] . '_';

        //Tạo mới
        $ads = Advertising::create($ads);

        flash(trans('ads.duplicate_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.edit',$ads->id));
    }


    /**
     * Xác nhận xóa quảng cáo
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm($id)
    {
        //Lấy ra quảng cáo cần xóa
        $ads = Advertising::findOrFail($id);

        return view('backend.ads.confirm', compact('ads'));
    }


    /**
     * Xóa quảng cáo
     *
     * @param $id
     */
    public function destroy($id)
    {
        //Lấy ra quảng cáo cần xóa
        $ads = Advertising::findOrFail($id);

        //Xóa
        $ads->delete();

        flash()->success(trans('common.success'), trans('ads.delete_success_message', ['name' => $ads->name]));

        return redirect(route('backend.ads.index'));
    }
}

app/Http/Controllers/Backend/AdsPositionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Advertising;
use App\Models\AdvertisingPosition;
use App\Http\Requests;

class AdsPositionController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ads_positions = AdvertisingPosition::paginate(15);

        return view('backend.ads_positions.index', compact('ads_position'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required',
            'slug'  => 'required',
        ]);

        AdvertisingPosition::create($request->all());

        flash()->success('Tạo vị trí quảng cáo thành công');

        return redirect(route('backend.adsposition.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use App\View\ThemeViewFinder;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Request;

abstract class Controller extends BaseController
{

    use ValidatesRequests;


    public function __construct()
    {
        $this->middleware('admin');
        if (session_id() == '') {
            @session_start();
            /* or Session:start(); */
        }
        $_SESSION['isLoggedIn'] = auth()->check() ? true : false;

    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php
/**
 * Created by PhpStorm.
 * User: Rain
* Date: 09/01/2016
* Time: 6:12 PM
*/

namespace App\Http\Controllers\Backend;

use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        return redirect(route('gallery.backend.albums.index'));

        $name = Route::getCurrentRoute()->getPath();
        return view('dashboard');
    }
}

resources/views/backend/orders/confirm.blade.php
@extends('main')

@section('title', 'Xóa đơn hàng #'.$order->id)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['backend.orders.destroy', $order->id]]) !!}

        <!-- Panel _start -->
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5>Xóa đơn hàng</h5>
        @include('partials.backend.heading-elements')
    </div>
    <div class="panel-body">
            <div class="alert alert-danger">
                <strong>Cảnh báo !</strong> Bạn đang muốn xóa  đơn hàng <strong>[#{{ $order->id }}]</strong>, việc này không thể phục hồi
            </div>

            {!! Form::submit('Vâng hãy xóa  đơn hàng này !', ['class' => 'btn btn-danger']) !!}

            <a href="{{ route('backend.orders.index') }}" class="btn btn-success">
                <strong>Không, đưa tôi trở lại!</strong>
            </a>
    </div>
</div><!-- Panel End -->

{!! Form::close() !!}

@endsection

resources/views/backend/orders/index.blade.php
@extends('main')

@section('title', 'Quản lý đơn hàng')


@section('content')


        <!-- Invoice grid -->
@if(count($orders) > 0)
    @foreach($orders->chunk(2) as $set)
        <div class="row">
            @foreach($set as $item)
                <div class="col-md-6">
                    <div class="panel invoice-grid">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h6 class="text-semibold no-margin-top"><a
                                                href="{{ route('backend.orders.show', $item->id) }}">{{ $item->user->name }}</a>
                                    </h6>
                                    <ul class="list list-unstyled">
                                        <li>Số phiếu #: &nbsp;{{ $item->id }}</li>
                                        <li>Ngày ra hóa đơn: <span
                                                    class="text-semibold">{{ format_date($item->created_at, 'd-m-Y') }}</span>
                                        </li>
                                    </ul>
                                </div>

                                <div class="col-sm-6">
                                    <h6 class="text-semibold text-right no-margin-top">{{ number_format(get_order_total($item)) }}
                                        đ</h6>
                                    <ul class="list list-unstyled text-right">
                                        <li>Phương thức thanh toán: <span
                                                    class="text-semibold">{{ $item->payment_method->name }}</span></li>
                                        <li class="dropdown">
                                            Trạng thái: &nbsp;
                                            <a href="#" class="label bg-{{ $item->status->color }} dropdown-toggle"
                                               data-toggle="dropdown">{{ $item->status->name }} <span
                                                        class="caret"></span></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                @foreach(get_order_statuses() as $status)
                                                    <li>
                                                        <a href="{{ route('backend.order.update_status', [$item->id, $status->id]) }}">{{ $status->name }}</a>
                                                    </li>
                                                @endforeach
                                                <li>
                                                    <a href="{{ route('backend.orders.confirm', $item->id) }}">Delete</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="panel-footer">
                            <ul>
                                <li><span class="status-mark border-blue position-left"></span> Nợ: <span
                                            class="text-semibold">{{ format_date($item->created_at, 'd-m-Y') }}</span>
                                </li>
                            </ul>

                            <ul class="pull-right">
                                <li><a href="{{ route('backend.orders.show', $item->id) }}"><i
                                                class="icon-eye8"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach
@else
    <p>Không có đơn hàng nào trên hệ thống</p>
    @endif
            <!-- /invoice grid -->


    <!-- Pagination -->
    <div class="text-center content-group-lg pt-20">
        {!! $orders->render() !!}
    </div>
    <!-- /pagination -->
    @endsection

resources/views/backend/orders/show.blade.php
@extends('main')

@section('title', 'Quản lý đơn hàng')


@section('content')

    <div class="panel panel-white">
        <div class="panel-heading">
            <h6 class="panel-title">Xem hóa đơn</h6>
            <a class="heading-elements-toggle"><i class="icon-menu"></i></a></div>

        <div class="panel-body no-padding-bottom">
            <div class="row">
                <div class="col-md-6 content-group">
                    <img src="{{ url() }}/assets/images/logo.png" class="content-group mt-10" alt="" style="width: 120px;">
                    <ul class="list-condensed list-unstyled">
                        <li>{{ get_settings('address') }}</li>
                    </ul>
                </div>

                <div class="col-md-6 content-group">
                    <div class="invoice-details">
                        <h5 class="text-uppercase text-semibold">Số phiều: #{{ $order->id }}</h5>
                        <ul class="list-condensed list-unstyled">
                            <li>Ngày ra phiếu: <span
                                        class="text-semibold">{{ get_vn_full_date($order->created_at) }}</span>
                            </li>
                            <li>Ngày quá hạn: <span
                                        class="text-semibold">{{ format_date($order->created_at,'d-m-Y', 3*24*3600) }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-lg-9 content-group">
                    <span class="text-muted">Khách hàng:</span>
                    <ul class="list-condensed list-unstyled">
                        <li><h5>{{ $order->user->name }}</h5></li>
                        <li><span class="text-semibold">{{ $order->user->address }}</span></li>
                        <li>{{ $order->user->district->name }}</li>
                        <li>{{ $order->user->province->name }}</li>
                        <li>{{ $order->user->phone }}</li>
                        <li><a href="#">{{ $order->user->email }}</a></li>
                    </ul>
                </div>

                <div class="col-md-6 col-lg-3 content-group">
                    <span class="text-muted">Thông tin thanh toán:</span>
                    <ul class="list-condensed list-unstyled invoice-payment-details">
                        <li><h5>Tổng tiền: <span class="text-right text-semibold">{{ number_format(get_order_total($order)) }}
                                    đ</span></h5></li>
                        <li>Phương thức thanh toán: <span
                                    class="text-semibold">{{ $order->payment_method->name }}</span></li>
                        <li>Trạng thái: <span>{{ $order->status->name }}</span></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-lg">
                <thead>
                <tr>
                    <th>Sản phẩm</th>
                    <th class="col-sm-1">Đơn giá</th>
                    <th class="col-sm-1">Số lượng</th>
                    <th class="col-sm-1">Tổng cộng</th>
                </tr>
                </thead>
                <tbody>
                @foreach($order->products()->get() as $item)

                    <tr>
                        <td>
                            <h6 class="no-margin">{{ $item->name }}</h6>
                            <span class="text-muted">
                                @foreach(get_order_options($item->pivot->id) as $key => $orderOption)
                                    {{ $orderOption->name }}: {{ $orderOption->value }},

                                @endforeach
                            </span>
                        </td>
                        <td>{{ number_format($item->pivot->price) }}</td>
                        <td>{{ $item->pivot->quantity }}</td>
                        <td><span class="text-semibold">{{ number_format($item->pivot->total) }}</span></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="panel-body">
            <div class="row invoice-payment">
                <div class="col-sm-5 col-sm-offset-7">
                    <div class="content-group">
                        <h6>Tổng cộng</h6>
                        <div class="table-responsive no-border">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>Subtotal:</th>
                                    <td class="text-right">{{ number_format(get_order_subtotal($order)) }} đ</td>
                                </tr>
                                <tr>
                                    <th>Tax: <span class="text-regular">(0%)</span></th>
                                    <td class="text-right">0 đ</td>
                                </tr>
                                <tr>
                                    <th>Total:</th>
                                    <td class="text-right text-primary"><h5
                                                class="text-semibold"> {{ number_format(get_order_total($order)) }}
                                            đ</h5></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                        @if($order->order_status_id == 1)
                            <div class="text-right">
                                <a href="{{ route('backend.order.update_status', [$order->id, 3]) }}" class="btn btn-danger">Đánh
                                    dấu hủy</a>
                                <a href="{{ route('backend.order.update_status', [$order->id, 15]) }}" class="btn btn-success">Đánh dấu
                                    đã thanh toán</a>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection